[package]
name = "ponlponl123-labs-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-ws = "0.3.0"
env_logger = "0.11.8"
futures-util = "0.3.31"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
